// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocaH1h-aOljuiLwntmR0FjWfa_umw-9U',
    appId: '1:1017817946014:web:7175f56bfc7850b75ba88f',
    messagingSenderId: '1017817946014',
    projectId: 'lds-1d3ec',
    authDomain: 'lds-1d3ec.firebaseapp.com',
    storageBucket: 'lds-1d3ec.firebasestorage.app',
    measurementId: 'G-SGMYG1TVM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6nZK0F2aEwSjnh_vQ1fEZl0dcRjQWjQg',
    appId: '1:1017817946014:android:b2009bc79975fb5a5ba88f',
    messagingSenderId: '1017817946014',
    projectId: 'lds-1d3ec',
    storageBucket: 'lds-1d3ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnaI6Dcg9WED262F-fcOiS7MjbNp5dfAs',
    appId: '1:1017817946014:ios:19877f12c5074ab45ba88f',
    messagingSenderId: '1017817946014',
    projectId: 'lds-1d3ec',
    storageBucket: 'lds-1d3ec.firebasestorage.app',
    iosBundleId: 'com.example.lds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnaI6Dcg9WED262F-fcOiS7MjbNp5dfAs',
    appId: '1:1017817946014:ios:19877f12c5074ab45ba88f',
    messagingSenderId: '1017817946014',
    projectId: 'lds-1d3ec',
    storageBucket: 'lds-1d3ec.firebasestorage.app',
    iosBundleId: 'com.example.lds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDocaH1h-aOljuiLwntmR0FjWfa_umw-9U',
    appId: '1:1017817946014:web:aa6c000005c80e195ba88f',
    messagingSenderId: '1017817946014',
    projectId: 'lds-1d3ec',
    authDomain: 'lds-1d3ec.firebaseapp.com',
    storageBucket: 'lds-1d3ec.firebasestorage.app',
    measurementId: 'G-LK26LT3GBR',
  );
}
